### ISSUE TITLE
Can't require the module without index.js on the root directory

### ISSUE THREAD

**Issue by yohei1126** [tony-o/harmony#3]
I required like this:

``` javascript
var harmony = require("node-harmony"); //awww, harmony
```

I got this error

``` javascript
Error: Cannot find module 'node-harmony'
14:38:11 web.1  |     at Function.Module._resolveFilename (module.js:338:15)
14:38:11 web.1  |     at Function.Module._load (module.js:280:25)
14:38:11 web.1  |     at Module.require (module.js:364:17)
14:38:11 web.1  |     at require (module.js:380:17)
14:38:11 web.1  |     at Object.<anonymous> (/Users/yohei/work/node-js-getting-started/app.js:121:15)
14:38:11 web.1  |     at Module._compile (module.js:456:26)
14:38:11 web.1  |     at Object.Module._extensions..js (module.js:474:10)
14:38:11 web.1  |     at Module.load (module.js:356:32)
14:38:11 web.1  |     at Function.Module._load (module.js:312:12)
14:38:11 web.1  |     at Function.Module.runMain (module.js:497:10)
14:38:11 web.1  | exited with code 8
14:38:11 system | sending SIGTERM to all processes
```

If I prepare index.js, it works.

**Comment by tony-o** [comment]
Merged commit to fix this

**Comment by yohei1126** [comment]
Thank you for merging.

**Comment by tony-o** [comment]
@yohei1126 thanks for the PR :+1:
