### ISSUE TITLE
Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by feraudet** [tony-o/harmony#7]
Hi,

I've these error using harmony. Have you an idea to avoid it ?

Regards,

``` javascript
(node) warning: possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Socket.addListener (events.js:179:15)
    at Socket.Readable.on (_stream_readable.js:671:33)
    at Socket.once (events.js:204:8)
    at Socket.Readable.pipe (_stream_readable.js:574:8)
    at Object.mater [as f] (/opt/lpn-milter/node/lib/node_modules/node-harmony/lib/server.js:40:10)
    at next (/opt/lpn-milter/node/lib/node_modules/node-harmony/node_modules/skoconc/skoconc.js:18:5)
    at Object.push (/opt/lpn-milter/node/lib/node_modules/node-harmony/node_modules/skoconc/skoconc.js:6:3)
    at Socket.<anonymous> (/opt/lpn-milter/node/lib/node_modules/node-harmony/lib/server.js:45:12)
    at Socket.emit (events.js:129:20)
    at net.js:459:14
(node) warning: possible EventEmitter memory leak detected. 12 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Socket.addListener (events.js:179:15)
    at Socket.Readable.on (_stream_readable.js:671:33)
    at Object.mater [as f] (/opt/lpn-milter/node/lib/node_modules/node-harmony/lib/server.js:51:9)
    at next (/opt/lpn-milter/node/lib/node_modules/node-harmony/node_modules/skoconc/skoconc.js:18:5)
    at Object.push (/opt/lpn-milter/node/lib/node_modules/node-harmony/node_modules/skoconc/skoconc.js:6:3)
    at Socket.<anonymous> (/opt/lpn-milter/node/lib/node_modules/node-harmony/lib/server.js:45:12)
    at Socket.emit (events.js:129:20)
    at net.js:459:14
    at process._tickCallback (node.js:355:11)
(node) warning: possible EventEmitter memory leak detected. 11 finish listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Socket.addListener (events.js:179:15)
    at Socket.Readable.on (_stream_readable.js:671:33)
    at Socket.once (events.js:204:8)
    at Socket.Readable.pipe (_stream_readable.js:580:8)
    at Object.mater [as f] (/opt/lpn-milter/node/lib/node_modules/node-harmony/lib/server.js:40:10)
    at next (/opt/lpn-milter/node/lib/node_modules/node-harmony/node_modules/skoconc/skoconc.js:18:5)
    at Object.push (/opt/lpn-milter/node/lib/node_modules/node-harmony/node_modules/skoconc/skoconc.js:6:3)
    at Socket.<anonymous> (/opt/lpn-milter/node/lib/node_modules/node-harmony/lib/server.js:45:12)
    at Socket.emit (events.js:129:20)
    at net.js:459:14
(node) warning: possible EventEmitter memory leak detected. 11 unpipe listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Socket.addListener (events.js:179:15)
    at Socket.Readable.on (_stream_readable.js:671:33)
    at Socket.Readable.pipe (_stream_readable.js:495:8)
    at Object.mater [as f] (/opt/lpn-milter/node/lib/node_modules/node-harmony/lib/server.js:40:10)
    at next (/opt/lpn-milter/node/lib/node_modules/node-harmony/node_modules/skoconc/skoconc.js:18:5)
    at Object.push (/opt/lpn-milter/node/lib/node_modules/node-harmony/node_modules/skoconc/skoconc.js:6:3)
    at Socket.<anonymous> (/opt/lpn-milter/node/lib/node_modules/node-harmony/lib/server.js:45:12)
    at Socket.emit (events.js:129:20)
    at net.js:459:14
    at process._tickCallback (node.js:355:11)
(node) warning: possible EventEmitter memory leak detected. 11 drain listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Socket.addListener (events.js:179:15)
    at Socket.Readable.on (_stream_readable.js:671:33)
    at Socket.Readable.pipe (_stream_readable.js:513:8)
    at Object.mater [as f] (/opt/lpn-milter/node/lib/node_modules/node-harmony/lib/server.js:40:10)
    at next (/opt/lpn-milter/node/lib/node_modules/node-harmony/node_modules/skoconc/skoconc.js:18:5)
    at Object.push (/opt/lpn-milter/node/lib/node_modules/node-harmony/node_modules/skoconc/skoconc.js:6:3)
    at Socket.<anonymous> (/opt/lpn-milter/node/lib/node_modules/node-harmony/lib/server.js:45:12)
    at Socket.emit (events.js:129:20)
    at net.js:459:14
    at process._tickCallback (node.js:355:11)
```

**Comment by tony-o** [comment]
Do you have some code for me to look at?  How many nodes are you connecting?
